name: Chat response suggestions
channels:
  - conda-forge
  - defaults
  - auto
dependencies:
  - python=3.9
  - jupyterlab==3.4.5
  - pandas==1.4.4
  - regex==2022.8.17
  - scikit-learn==1.1.2
  - scipy==1.9.1
  - seaborn==0.11.2
  - matplotlib==3.5.2
  - make=4.3
  - openpyxl==3.0.9
  - python-dotenv==0.21.0
  - pyodbc==4.0.34
  - pip==22.2.2
  - requests==2.27.1
  - pip:
    - -e .  # make the project editable package, conda >= 4.4 only
    - --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org # to avoid problems with proxies
    - django-health-check
  # - djangorestframework==3.14.0
  # - django==4.1
  # - celery==5.2.7
  # - dj-database-url==1.2.0
  # - django-filter==22.1
  # - whitenoise==6.3.0
  # - furl==2.1.2
  # - environs==9.5.0

  - Django==4.0.2
  - environs==9.5.0
  - furl==2.1.3
  - djangorestframework==3.13.1
  - django-filter==21.1
  - django_polymorphic==3.1.0
  - django-cors-headers==3.11.0
  - drf-yasg==1.20.0
  - django-rest-polymorphic==0.1.9
  - chardet==4.0.0
  - pyexcel==0.7.0
  - seqeval==1.2.2
  - whitenoise==6.3.0
  - dj-database-url==0.5.0
  - pyexcel-xlsx==0.6.0
  - auto-labeling-pipeline==0.1.21
  - dj-rest-auth==2.2.5
  - django-drf-filepond==0.4.1
  - celery==5.2.3
  - SQLAlchemy==1.4.31
  - waitress==2.0.0
  - djangorestframework-xml==2.0.0
  - django-storages==1.13.1
  - django-cleanup==6.0.0
  - filetype==1.0.10
  - flower==1.2.0
  - django-allauth==0.50.0



